# my-app/values.yaml
replicaCount: 1

image:
  repository: 77antonovqwertyop77/my-nginx-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: ""
  annotations: {}
  host: <ваш_домен>
  path: /
  pathType: ImplementationSpecific
  tls: []
